// <auto-generated />
// Copyright (c) Fantasy Copilot. All rights reserved.

using System.Text.Json.Serialization;
using CsvHelper.Configuration.Attributes;

namespace FantasyCopilot.Models.App.Web;

public sealed class AwesomePromptItem
{
    [JsonPropertyName("act")]
    [Index(0)]
    public string Act { get; set; }

    [JsonPropertyName("prompt")]
    [Index(1)]
    public string Prompt { get; set; }
}
