// Copyright (c) Fantasy Copilot. All rights reserved.
// <auto-generated />

using System.Text.Json.Serialization;

namespace FantasyCopilot.Models.App.Web;

/// <summary>
/// Civitai tag search result.
/// </summary>
public sealed class CivitaiTagSearchResult
{
    [JsonPropertyName("items")]
    public List<CivitaiTag> Items { get; set; }

    [JsonPropertyName("metadata")]
    public CivitaiSearchMetadata Metadata { get; set; }
}

/// <summary>
/// Civitai image search result.
/// </summary>
public sealed class CivitaiImageSearchResult
{
    [JsonPropertyName("items")]
    public List<CivitaiImage> Items { get; set; }

    [JsonPropertyName("metadata")]
    public CivitaiSearchMetadata Metadata { get; set; }
}

/// <summary>
/// Civitai search meta data.
/// </summary>
public sealed class CivitaiSearchMetadata
{
    [JsonPropertyName("totalItems")]
    public int TotalItems { get; set; }

    [JsonPropertyName("currentPage")]
    public int CurrentPage { get; set; }

    [JsonPropertyName("pageSize")]
    public int PageSize { get; set; }

    [JsonPropertyName("totalPages")]
    public int TotalPages { get; set; }

    [JsonPropertyName("nextPage")]
    public string NextPageLink { get; set; }
}

public class CivitaiTag
{
    [JsonPropertyName("name")]
    public string Name { get; set; }

    [JsonPropertyName("modelCount")]
    public int ModelCount { get; set; }
}


public class CivitaiImage
{
    [JsonPropertyName("id")]
    public long Id { get; set; }

    [JsonPropertyName("url")]
    public string Url { get; set; }

    [JsonPropertyName("width")]
    public int Width { get; set; }

    [JsonPropertyName("height")]
    public int Height { get; set; }

    [JsonPropertyName("nsfw")]
    public bool Nsfw { get; set; }

    [JsonPropertyName("createdAt")]
    public DateTimeOffset CreatedAt { get; set; }

    [JsonPropertyName("postId")]
    public long PostId { get; set; }

    [JsonPropertyName("stats")]
    public CivitaiItemStats Stats { get; set; }

    [JsonPropertyName("meta")]
    public CivitaiImageMetadata Meta { get; set; }

    [JsonPropertyName("username")]
    public string UserName { get; set; }
}

public class CivitaiItemStats
{
    [JsonPropertyName("cryCount")]
    public int CryCount { get; set; }

    [JsonPropertyName("laughCount")]
    public int LaughCount { get; set; }

    [JsonPropertyName("likeCount")]
    public int LikeCount { get; set; }

    [JsonPropertyName("dislikeCount")]
    public int DislikeCount { get; set; }

    [JsonPropertyName("heartCount")]
    public int HeartCount { get; set; }

    [JsonPropertyName("commentCount")]
    public int CommentCount { get; set; }
}

public class CivitaiImageMetadata
{
    [JsonPropertyName("seed")]
    public long Seed { get; set; }

    [JsonPropertyName("Model")]
    public string Model { get; set; }

    [JsonPropertyName("steps")]
    public int Steps { get; set; }

    [JsonPropertyName("prompt")]
    public string Prompt { get; set; }

    [JsonPropertyName("sampler")]
    public string Sampler { get; set; }

    [JsonPropertyName("cfgScale")]
    public double CfgScale { get; set; }

    [JsonPropertyName("Clip skip")]
    public string ClipSkip { get; set; }

    [JsonPropertyName("negativePrompt")]
    public string NegativePrompt { get; set; }

    [JsonPropertyName("Noise multiplier")]
    public string NoiseMultiplier { get; set; }

    [JsonPropertyName("Denoising strength")]
    public string DenoisingStrength { get; set; }
}
