// Copyright (c) Fantasy Copilot. All rights reserved.
// <auto-generated />

using System.Text.Json.Serialization;

namespace FantasyCopilot.Models.App.Web;

public sealed class OpenAIDeploymentResponse
{
    [JsonPropertyName("data")]
    public List<OpenAIDeployment> Data { get; set; }
}

public sealed class OpenAIDeployment
{
    [JsonPropertyName("model")]
    public string Model { get; set; }

    [JsonPropertyName("id")]
    public string Id { get; set; }
}
