// <auto-generated />


namespace FantasyCopilot.Libs.Everything.Interfaces
{
    public enum SortingKey
    {
        None = 0,
        NameAscending = 1,
        NameDescending = 2,
        PathAscending = 3,
        PathDescending = 4,
        SizeAscending = 5,
        SizeDescending = 6,
        ExtensionAscending = 7,
        ExtensionDescending = 8,
        TypeNameAscending = 9,
        TypeNameDescending = 10,
        DateCreatedAscending = 11,
        DateCreatedDescending = 12,
        DateModifiedAscending = 13,
        DateModifiedDescending = 14,
        AttributesAscending = 15,
        AttributesDescending = 16,
        FileListFilenameAscending = 17,
        FileListFilenameDescending = 18,
        RunCountAscending = 19,
        RunCountDescending = 20,
        DateRecentlyChangedAscending = 21,
        DateRecentlyChangedDescending = 22,
        DateAccessedAscending = 23,
        DateAccessedDescending = 24,
        DateRunAscending = 25,
        DateRunDescending = 26,
    }
}
