// Copyright (c) Fantasy Copilot. All rights reserved.
// <auto-generated />

using System;
using System.Text;

namespace Microsoft.Toolkit.Parsers.Markdown.Blocks
{
    internal class ListItemBuilder : MarkdownBlock
    {
        public StringBuilder Builder { get; } = new StringBuilder();

        public ListItemBuilder()
            : base(MarkdownBlockType.ListItemBuilder)
        {
        }
    }
}
