// <auto-generated />

using System;

namespace Microsoft.Toolkit.Parsers.Markdown.Blocks
{
    internal class ListItemPreamble
    {
        public ListStyle Style { get; set; }

        public int ContentStartPos { get; set; }
    }
}
