// Copyright (c) Fantasy Copilot. All rights reserved.
// <auto-generated />

namespace FantasyCopilot.Models.Constants;

public static class ConnectorConstants
{
    public const string DefaultConnectorFolderName = "Connectors";
    public const string ConnectorConfigFileName = "connector.json";
    public const string ConnectorCacheFileName = "ConnectorCache.json";
    public const string ConnectorExtension = ".fctor";

    public const string ChatType = "chat";
    public const string ChatRestType = "chat-rest";
    public const string ChatStreamType = "chat-stream";
    public const string ChatStreamCancelType = "chat-stream-cancel";

    public const string TextCompletionType = "text-completion";
    public const string TextCompletionRestType = "text-completion-rest";
    public const string TextCompletionStreamType = "text-completion-stream";
    public const string TextCompletionStreamCancelType = "text-completion-stream-cancel";

    public const string EmbeddingType = "embedding";
    public const string EmbeddingRestType = "embedding-rest";
}
