// <auto-generated />
// Copyright (c) Fantasy Copilot. All rights reserved.

namespace FantasyCopilot.Models.Constants;

public static class WorkflowConstants
{
    public static class Chat
    {
        public const string InitializeName = "Chat_Initialize";
        public const string InitializeDescription = "Initialize the chat message pipeline.";
        public const string SendName = "Chat_Send";
        public const string SendDescription = "Send a message to the LLM.";
        public const string GenerateStreamName = "Chat_GenerateStream";
        public const string GenerateStreamDescription = "Send a message to the LLM and get stream response.";
    }

    public static class TextCompletion
    {
        public const string InitializeName = "TextCompletion_Initialize";
        public const string InitializeDescription = "Initialize the text completion pipeline.";
        public const string CompleteName = "TextCompletion_Complete";
        public const string CompleteDescription = "Complete the given text.";
        public const string CompleteStreamName = "TextCompletion_CompleteStream";
        public const string CompleteStreamDescription = "Complete the given text and get stream response.";
    }

    public static class Text
    {
        public const string TranslateName = "Text_Translate";
        public const string TranslateDescription = "Translate the given text into another language.";
        public const string OverwriteName = "Text_Overwrite";
        public const string OverwriteDescription = "Overwrites the input text in the pipeline and outputs the new text.";
        public const string VariableRedirectName = "Text_VariableRedirect";
        public const string VariableRedirectDescription = "Copy the value of one variable in the context to another variable.";
        public const string VariableCreateName = "Text_VariableCreate";
        public const string VariableCreateDescription = "Create a new variable and insert into context.";
    }

    public static class Voice
    {
        public const string ReadTextName = "Voice_ReadText";
        public const string ReadTextDescription = "Convert the given text to speech.";
    }

    public static class Image
    {
        public const string DrawName = "Image_Draw";
        public const string DrawDescription = "Convert the given prompt into an image.";
    }

    public static class Knowledge
    {
        public const string GetKnowledgeName = "Knowledge_Get";
        public const string GetKnowledgeDescription = "Gets information from the specified knowledge base.";
        public const string ImportFileName = "Knowledge_ImportFile";
        public const string ImportFileDescription = "Imports the specified file into the knowledge base.";
        public const string ImportFolderName = "Knowledge_ImportFolder";
        public const string ImportFolderDescription = "Imports the specified folder into the knowledge base.";
    }

    public static class Input
    {
        public const string TextName = "Input_Text";
        public const string TextDescription = "Get the text content entered by the user.";
        public const string VoiceName = "Input_Voice";
        public const string VoiceDescription = "Transcribe the user's voice through the microphone.";
        public const string FileName = "Input_File";
        public const string FileDescription = "Get file(s) imported or opened by the user.";
    }

    public static class Output
    {
        public const string TextName = "Output_Text";
        public const string TextDescription = "Output the generated text. This is usually the preferred way to output.";
        public const string VoiceName = "Output_Voice";
        public const string VoiceDescription = "Play the specified audio content.";
        public const string ImageName = "Output_Image";
        public const string ImageDescription = "Render the specified image.";
    }

    public static class Native
    {
        public const string TextNotificationName = "Native_TextNotification";
        public const string TextNotificationDescription = "Send a system notification to the user.";
    }

    public const int ErrorKey = -404;
    public const string LinkKey = "LINK";
    public const string StepResultKey = "STEP_RESULT_{0}";
    public const string Txt2ImgResultKey = "TEXT_TO_IMAGE_{0}";
    public const string KnowledgeSourceKey = "KNOWLEDGE_SOURCE_{0}";
    public const string OriginalKey = "ORIGINAL";

    public const string QAPrompt = """
        {{$Content}}
        ---
        Answer user questions concisely and professionally based only on known information above.
        If you can't get an answer out of it, please let me know that you can't answer the question, no fabrication is allowed in the answer.
        Question: {{$input}}
        Answer:
        """;
    public const string QADescription = "Answer the question.";
    public const string QASkillId = "QASKILL";

    public const string GlobalFunctions = "_GLOBAL_FUNCTIONS_";
    public const string PluginConfigFileName = "config.json";
    public const string DefaultPluginFolderName = "Plugins";
    public const string PluginExtension = ".fcpkg";

    public const string TextGroupName = "text";
    public const string FileGroupName = "file";
    public const string WebGroupName = "web";
    public const string ImageGroupName = "image";
    public const string VideoGroupName = "video";
    public const string VoiceGroupName = "voice";
    public const string NativeGroupName = "native";
    public const string A11yGroupName = "accessibility";
    public const string ToolGroupName = "tool";
    public const string OtherGroupName = "other";
    public const string KnowledgeGroupName = "knowledge";

    public const string InputConfigName = "input";
    public const string OptionConfigName = "option";
}
