// Copyright (c) Fantasy Copilot. All rights reserved.
// <auto-generated />

using Microsoft.SemanticKernel.SkillDefinition;
using FantasyCopilot.Models.Constants;

namespace FantasyCopilot.Libs.NativeSkills;

/// <summary>
/// Placeholder skills.
/// </summary>
public sealed class PlaceholderSkill
{
    [SKFunctionName(WorkflowConstants.Input.TextName)]
    [SKFunction(WorkflowConstants.Input.TextDescription)]
    public static void InputText()
    {
    }

    [SKFunctionName(WorkflowConstants.Input.VoiceName)]
    [SKFunction(WorkflowConstants.Input.VoiceDescription)]
    public static void InputVoice()
    {
    }

    [SKFunctionName(WorkflowConstants.Input.FileName)]
    [SKFunction(WorkflowConstants.Input.FileDescription)]
    public static void InputFile()
    {
    }

    [SKFunctionName(WorkflowConstants.Output.TextName)]
    [SKFunction(WorkflowConstants.Output.TextDescription)]
    public static void OutputText()
    {
    }

    [SKFunctionName(WorkflowConstants.Output.VoiceName)]
    [SKFunction(WorkflowConstants.Output.VoiceDescription)]
    public static void OutputVoice()
    {
    }

    [SKFunctionName(WorkflowConstants.Output.ImageName)]
    [SKFunction(WorkflowConstants.Output.ImageDescription)]
    public static void OutputImage()
    {
    }
}
