// Copyright (c) Fantasy Copilot. All rights reserved.
// <auto-generated />

using System;
using System.Text.Json.Serialization;

namespace FantasyCopilot.Services;

/// <summary>
/// HTTP schema to perform completion request.
/// </summary>
[Serializable]
public sealed class TextCompletionRequest
{
    /// <summary>
    /// Prompt to complete.
    /// </summary>
    [JsonPropertyName("inputs")]
    public string Input { get; set; } = string.Empty;
}
