// Copyright (c) Fantasy Copilot. All rights reserved.
// <auto-generated />

using System.Text.Json.Serialization;

namespace FantasyCopilot.Services;

/// <summary>
/// HTTP Schema for completion response.
/// </summary>
public sealed class TextCompletionResponse
{
    /// <summary>
    /// Completed text.
    /// </summary>
    [JsonPropertyName("generated_text")]
    public string Text { get; set; }
}
